
/*   Menu items definitions
*/
#define ID_MAINWND      256
#define ID_SLIDER       257
#define ID_OPTIONS      257
#define ID_EXIT         259
#define ID_BOOM         260
#define ID_LAND         261
#define ID_DEATH        262
#define ID_COLLISION    263
#define ID_START        264
#define ID_STOP         265
#define ID_ADJUST       266

#define PB_OK           107
#define PB_APPLY        108
#define PB_CANCEL       109

#define EF_PRIMARY      101
#define EF_AUTO         105
#define EF_PLAYER   106

#define IDM_POWER_ONE   2000
#define PB_OK           107
#define PB_APPLY        108
#define PB_CANCEL       109

#define EF_PRIMARY      101
#define EF_AUTO         105
#define EF_PLAYER       106
#define DLG_ADJ         999

#define DLG_GAME_INFO               100
#define TX_SCORE                    103
#define TX_MESSAGE                  104
#define EF_GAME_SPEED               113
#define EF_SCROLL_SPEED             114
#define TXT_JOY_X                   5001
#define TXT_JOY_Y                   5000
#define Y Mov:                      116
#define TXT_MOV_X                   117
#define TXT_MOV_Y                   118
#define TXT_BUT_1                   119
#define TXT_BUT_2                   120
#define TXT_SPEED                   125
#define TXT_WEAPON_TYPE             123
#define TXT_MEMORY                  127
#define Threads                     129
#define TXT_THREADS                 130
#define TXT_CUR_X                   133
#define TXT_CUR_Y                   134
#define TXT_TOT_SPRITES             136
#define TXT_TOT_ACTIVE              138
#define TXT_FRAMES                  139
#define CK_BLANK                    140
#define TXT_FRAME_HIGH              121
#define TXT_FRAME_LOW               141
#define PB_CLEAR                    151
#define CK_DIVEBLIT                 116
#define TXT_MESSAGE                 145
